apiVersion: v1
kind: Pod
metadata:
  name: smart-mvn-agent
spec:
  hostAliases:
  - ip: "192.168.0.200"
    hostnames:
    - "jenkins.s3t.co"
    - "tunnel.jenkins.s3t.co"
    - "nexus.s3t.co"
    - "docker-s.nexus.s3t.co"
    - "docker-r.nexus.s3t.co"
    - "docker-p.nexus.s3t.co"
    - "docker-g.nexus.s3t.co"
  - ip: "192.168.0.240"
    hostnames:
    - "kmaster.com"
  containers:
  - name: smart-mvn-agent
    image: docker-r.nexus.s3t.co/smart-mvn-agent:latest
    command:
    - cat
    tty: true
    env:
      - name: REGISTRY_USERNAME # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: nexus-s3-co-secret
            key: username
      - name: REGISTRY_PASSWORD # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: nexus-s3-co-secret
            key: password
      - name: MVN_REGISTRY_GROUP # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-mvn-agent-env
            key: public
      - name: MVN_REGISTRY_RELEASE # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-mvn-agent-env
            key: release
      - name: MVN_REGISTRY_SNAPSHOOT # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-mvn-agent-env
            key: snapshoot
      - name: DOCKER_REGISTRY_GROUP # image parameter for pom.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-skaffold-agent-env
            key: public
      - name: DOCKER_REGISTRY_RELEASE # image parameter for pom.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-skaffold-agent-env
            key: release
      - name: DOCKER_REGISTRY_SNAPSHOOT # image parameter for pom.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-skaffold-agent-env
            key: snapshoot
  - name: smart-skaffold-agent
    image: docker-r.nexus.s3t.co/smart-skaffold-agent:latest
    command:
    - cat
    tty: true
    env:
      - name: REGISTRY_USERNAME # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: nexus-s3-co-secret
            key: username
      - name: REGISTRY_PASSWORD # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: nexus-s3-co-secret
            key: password
      - name: MVN_REGISTRY_GROUP # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-mvn-agent-env
            key: public
      - name: MVN_REGISTRY_RELEASE # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-mvn-agent-env
            key: release
      - name: MVN_REGISTRY_SNAPSHOOT # image parameter for settings.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-mvn-agent-env
            key: snapshoot
      - name: DOCKER_REGISTRY_GROUP # image parameter for pom.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-skaffold-agent-env
            key: public
      - name: DOCKER_REGISTRY_RELEASE # image parameter for pom.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-skaffold-agent-env
            key: release
      - name: DOCKER_REGISTRY_SNAPSHOOT # image parameter for pom.xml
        valueFrom:
          secretKeyRef:
            name: jenkins-skaffold-agent-env
            key: snapshoot
  imagePullSecrets:
    - name: nexus-s3t-co-docker-config